### ISSUE TITLE
Expired TLS certificate

### ISSUE THREAD

**Issue by ben-kap** [braindecode/braindecode.github.io#2]
The TLS certificate for braindecode.org has expired. Since the site is hosted with Github Pages, I imagine this needs to be clarified via Github. 
<img width="261" alt="image" src="https://user-images.githubusercontent.com/79790398/184123293-f8ac32e6-cadf-4463-b01a-228f2f8da035.png">

**Comment by robintibor** [comment]
Thanks so much for your comment! 
It is now fixed. 

For the record, I tried redoing through the steps at:
https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain
and understanding
https://github.com/isaacs/github/issues/1675

More concretely, I changed A record,  added AAAA record, as well as added CNAME on provider linking www.braindecode.org to braindecode.github.io. I also changed CNAME here (adding also www.braindecode.org). 
Not clear what exactly was the crucial part.
